//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temporal.Sdk.StubGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TemporalStubGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Temporal.Sdk.Generated
        ///{
        ///    public class Template__ConsolePrinter__
        ///    {
        ///        private readonly string _prefix;
        ///
        ///        public Template__ConsolePrinter__(string prefix)
        ///        {
        ///            _prefix = prefix ?? String.Empty;
        ///        }
        ///
        ///        public void WriteLine()
        ///        {
        ///            Console.WriteLine();
        ///        }
        ///
        ///        public void WriteLine(string msg)
        ///        {
        ///            msg ??= String.Empty;
        ///            Console.WriteLine($&quot;[{_prefix}]!! {msg}&quot;) [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Template__ConsolePrinter__ {
            get {
                return ResourceManager.GetString("Template__ConsolePrinter__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #region MAIN_TEMPLATE
        ///using System;
        ///using System.Threading;
        ///using System.Threading.Tasks;
        ///using Temporal.Sdk.StubGenerator.MOckSdkDependencies;
        ///
        ///namespace __Namespace_Template__
        ///{
        ///    /// &lt;summary&gt;
        ///    /// This class is an auto=generated stub for &lt;see cref=&quot;__WorkflowImplementationType_Template__&quot; /&gt;
        ///    /// (in assembly &quot;__WorkflowImplementationTypeAsm_Template__&quot;).
        ///    /// &lt;/summary&gt;
        ///    internal partial class __WorkflowStubClass_Template__
        ///    {
        ///        private readonly IWorkflowHandle _wor [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Template__WorkflowStub__ {
            get {
                return ResourceManager.GetString("Template__WorkflowStub__", resourceCulture);
            }
        }
    }
}
