using System;
using System.IO;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Temporal.Sdk.StubGenerator
{
    [Generator]
    public class ConsolePrinterGenerator : ISourceGenerator
    {
        public void Execute(GeneratorExecutionContext context)
        {
            //string src = File.ReadAllText(PoC_Hardcodings.SourceBaseDir
            //                            + @"\TemporalStubGenerator\Temporal.Sdk.AutoGeneratedCodeTemplates\Template__ConsolePrinter__.cs");

            string src = Resources.Template__ConsolePrinter__;

            src = src.Replace("Template__ConsolePrinter__", "ConsolePrinter");

            context.AddSource("ConsolePrinter.g.cs", SourceText.From(src, Encoding.UTF8));
        }

        public void Initialize(GeneratorInitializationContext context)
        {    
        }
    }
}
